<?php
return [
    [
        'id' => 1,
        'method' => 'GET',
        'path' => '/user/{id}',
		'page_hidden'=>false,
		'page_title'=>'Заголовок',
		'page_title_spare'=>'Альтернативный Заголовок',
		'page_meta_keywords'=> null,
        'page_meta_description'=> null,
        'controller' => [MainApp\Controllers\UserController::class, 'index'],
        'basetemplate' => null,
		'contentfile'=>null,
        'parent_id_page' => null,
		'needauth' => false,
		'onlyforguest'=> false,
		'priority'=>0,
        'layer' => 1		
    ],
    [
        'id' => 2,  
        'method' => 'GET',
        'path' => '/',
		'page_hidden'=>false,
		'page_title'=>'Заголовок',
		'page_title_spare'=>'Альтернативный Заголовок',
		'page_meta_keywords'=> null,
        'page_meta_description'=> null,
        'controller' => [MainApp\Controllers\IndexController::class, 'index'],
        'basetemplate' => null,
		'contentfile'=>null,
        'parent_id_page' => null,
		'needauth' => false,
		'onlyforguest'=> false,
		'priority'=>0,
        'layer' => 1  
    ],
    [
        'id' => 3,  
        'method' => 'GET',
        'path' => '/дом',
		'page_hidden'=>false,
		'page_title'=>'Заголовок',
		'page_title_spare'=>'Альтернативный Заголовок',
		'page_meta_keywords'=> null,
        'page_meta_description'=> null,
        'controller' => ['home', 'index'],
        'middlewares' => [Core\Middlewares\AuthMiddleware::class, 'handleRequest'],
        'basetemplate' => null,
		'contentfile'=>null,
        'parent_id_page' => 2,
		'needauth' => true,
		'onlyforguest'=> false,
		'priority'=>0,
        'layer' => 2  
    ],
    [
        'id' => 4,  
        'method' => 'GET',
        'path' => '/test/test/test',
		'page_hidden'=>false,
		'page_title'=>'Заголовок',
		'page_title_spare'=>'Альтернативный Заголовок',
		'page_meta_keywords'=> null,
        'page_meta_description'=> null,
        'controller' => ['', 'index'],
        'middlewares' => [Core\Middlewares\AuthMiddleware::class, 'handleRequest'],
        'basetemplate' => null,
		'contentfile'=>null,
        'parent_id_page' => 3,
		'needauth' => false,
		'onlyforguest'=> false,
		'priority'=>0,
        'layer' => 3  
    ],
	 [
        'id' => 5,  
        'method' => 'GET',
        'path' => '/@user{id}',
		'page_hidden'=>false,
		'page_title'=>'Заголовок',
		'page_title_spare'=>'Альтернативный Заголовок',
		'page_meta_keywords'=> null,
        'page_meta_description'=> null,
        'controller' => ['test', 'index'],
        'middlewares' => [Core\Middlewares\AuthMiddleware::class, 'handleRequest'],
        'basetemplate' => null,
		'contentfile'=>null,
        'parent_id_page' => null,
		'needauth' => false,
		'onlyforguest'=> false,
		'priority'=>0,
        'layer' => 1  
    ]
];